### ISSUE TITLE
Liscensing?

### ISSUE THREAD

**Issue by cheako** [tritone11/ethereum-rust-utils#1]
Looks like the mnemonic code is a copy of Apache 2.0 from here https://github.com/emeraldpay/emerald-vault/blob/master/src/mnemonic/language.rs

It dosn't look good for there to be a conflict like this.

**Comment by tritone11** [comment]
Hello cheako, yes, you're right, it's also a very bad crate with a lot of stuff pasted together when I was starting to approach to rust and learning, and it's even not useful. I am just gonna archive it. Thank you
